default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [main, layout, partials, backend]

  javascripts:    []

  has_layout:     on
  layout:         layout
