matchDonationsSuccess:
  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype]

addBulkSuccess:
  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, %SF_PROTOTYPE_WEB_DIR%/js/effects]

uploadBulkSuccess:
  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, %SF_PROTOTYPE_WEB_DIR%/js/effects]

editExternalKeysSuccess:
  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, %SF_PROTOTYPE_WEB_DIR%/js/effects]
  
editCustomFieldsSuccess:
  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype]
  
mapSuccess:
  javascripts:    [d3.v3.min.js, jquery.min.js, netmap.js]

interlocksMapSuccess:
  javascripts:    [d3.v3.min.js, jquery.min.js, netmap.js]