default:
  is_secure: on
  credentials: importer
  
save:
  is_secure: on
  credentials: importer

edit:
  is_secure: on
  credentials: importer

delete:
  is_secure: on
  credentials: importer
  
list:
  is_secure: on
  credentials: importer


